import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/app/TopNav";
import { garamond } from "./fonts";

export const metadata: Metadata = {
  title: "Adam Kiryk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamond.className}`}>
        <a href="#main" className="sr-only focus:not-sr-only">
          Skip To Main
        </a>{" "}
        <TopNav />
        <main id="main" className="mx-4">
          {children}
        </main>
      </body>
    </html>
  );
}
