import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Adam Kiryk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-caslon text-gray antialiased">
        <a href="#main" className="sr-only focus:not-sr-only">
          Skip To Main
        </a>
        <div className="grid grid-cols-[2rem_1fr_2rem] md:grid-cols-[4rem_1fr_4rem]">
          {children}
          <section className="col-start-1 col-end-4">
            <Footer />
          </section>
        </div>
      </body>
    </html>
  );
}
