import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/app/TopNav";

export const metadata: Metadata = {
  title: "Adam Kiryk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-caslon text-gray antialiased">
        <a href="#main" className="sr-only focus:not-sr-only">
          Skip To Main
        </a>{" "}
        <div className="mx-8">
          <TopNav />
        </div>
        <main id="main" className="mx-8 lg:mx-16">
          {children}
        </main>
      </body>
    </html>
  );
}
